WatchedItWeb/Pages/Movies/AddMovie.cshtml.cs
    using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using ClassLibraries.interfaces;
using ClassLibraries.models;
using ClassLibraries.services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WatchedItWeb.Pages.Movies
{
    public class AddMovieModel : PageModel
    {
        private readonly INotyfService _notyf;
        private readonly IMovieService _movieService;
        private readonly IEpisodeService _episodeService;

        [BindProperty]
        public Movie movie { get; set; }
        
        [BindProperty(SupportsGet = true)]
        public bool m { get; set; }

        [BindProperty(SupportsGet = true)]
        public int seriesId { get; set; }
        public AddMovieModel(INotyfService notyf, IMovieService movieService, IEpisodeService episodeService)
        {
            _notyf = notyf;
            _movieService = movieService;
            _episodeService = episodeService;
        }
        public IActionResult OnGet()
        {
            if (HttpContext.Session.IsAdmin() != true)
            {
                return RedirectToPage("/Index");
            }
            try
            {
                if (seriesId <= 0 && !m)
                {
                    return RedirectToPage("/Index");
                }
                else if (seriesId > 0 && !m)
                {
                    Series foundSeries = SeriesService.GetSeriesById(seriesId);
                    if (foundSeries == null)
                    {
                        return RedirectToPage("/Index");
                    }
                    else
                    {
                        return Page();
                    }
                }
                else
                {
                    return Page();
                }
            }
            catch (Exception ex)
            {
                _notyf.Error(ex.Message);
                return RedirectToPage("/Index");
            }
        }
        public IActionResult OnPost()
        {
            try
            {
                if (m)
                {
                    _movieService.AddMovie(HttpContext.Session.GetLoggedUser(), movie.Name, movie.Year.ToString(), movie.ImageUrl, movie.Genre, movie.Producer, movie.Description, movie.Actors, movie.Duration.ToString());
                    _notyf.Success("Movie added!");
                    return RedirectToPage("/Movies/AllMovies");
                }
                else
                {
                    if (String.IsNullOrEmpty(Request.Form["episode"]))
                    {
                        throw new Exception("You must enter an episode.");
                    }
                    if (String.IsNullOrEmpty(Request.Form["season"]))
                    {
                        throw new Exception("You must enter a season.");
                    }
                    int episode = Convert.ToInt32(Request.Form["episode"]);
                    int season = Convert.ToInt32(Request.Form["season"]);
                    _episodeService.AddEpisode(HttpContext.Session.GetLoggedUser(), movie.Name, movie.Year.ToString(), movie.ImageUrl, movie.Genre, movie.Producer, movie.Description, movie.Actors, movie.Duration.ToString(), season, episode, seriesId); ;
                    _notyf.Success("Episode added!");
                    return RedirectToPage("/Serie/SeriesDetails" , new { seriesId = seriesId });
                }

            }
            catch (Exception ex)
            {
                _notyf.Error(ex.Message);
                return Page();
            }

        }
    }
}

WatchedItWeb/Pages/Movies/AllMovies.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ClassLibraries.models;
using ClassLibraries.services;
using AspNetCoreHero.ToastNotification.Abstractions;
using ClassLibraries.interfaces;

namespace WatchedItWeb.Pages.Movies
{
    public class AllMoviesModel : PageModel
    {
        private readonly INotyfService _notyf;
        private readonly IMovieService _movieService;
        public List<Movie> movies = new List<Movie>();
        [BindProperty(SupportsGet = true)]
        public int CurrentPage { get; set; } = 0;
        [BindProperty(SupportsGet = true)]
        public string keyword { get; set; }
        public AllMoviesModel(INotyfService notyf, IMovieService movieService)
        {
            _notyf = notyf;
            _movieService = movieService;
        }
        public void OnGet()
        {
            try
            {
                if (!string.IsNullOrEmpty(keyword))
                {
                    movies = _movieService.SearchMovies(keyword);
                }
                else
                {
                    List<Movie> loadedMovies = new List<Movie>();
                    for (int i = 0; i <= CurrentPage; i++)
                    {
                        loadedMovies = _movieService.GetMovies(i * 4);
                        movies.AddRange(loadedMovies);
                    }
                }
            }
            catch (Exception ex)
            {
                _notyf.Error(ex.Message);
            }

        }
        public void OnPost()
        {

        }
    }
}

WatchedItWeb/Pages/Movies/EditMovie.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using ClassLibraries.interfaces;
using ClassLibraries.models;
using ClassLibraries.services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WatchedItWeb.Pages.Movies
{
    public class EditMovieModel : PageModel
    {
        private readonly INotyfService _notyf;
        private readonly IMovieService _movieService;
        private readonly IEpisodeService _episodeService;

        [BindProperty]
        public Movie movie { get; set; }

        [BindProperty(SupportsGet = true)]
        public bool m { get; set; }

        [BindProperty(SupportsGet = true)]
        public int movieId { get; set; }
        public EditMovieModel(INotyfService notyf, IMovieService movieService, IEpisodeService episodeService)
        {
            _notyf = notyf;
            _movieService = movieService;
            _episodeService = episodeService;
        }
        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetLoggedUser() == null || HttpContext.Session.GetLoggedUser().IsAdmin == false)
            {
                _notyf.Error("You are not authorized");
                return RedirectToPage("/Index");
            }
            try
            {
                if (m)
                {
                    movie = _movieService.GetMovieById(movieId);
                }
                else
                {
                    movie = _episodeService.GetEpisodeById(movieId);
                }

                if (movie == null)
                {
                    _notyf.Error("Resource not found!");
                    return RedirectToPage("/Movies/AllMovies");
                }
                return Page();
            }
            catch (Exception ex)
            {
                _notyf.Error(ex.Message);
                return RedirectToPage("/Index");
            }
        }
        public IActionResult OnPost()
        {
            try
            {                
                if (m)
                {
                    _movieService.EditMovieOrEpisode(HttpContext.Session.GetLoggedUser(), movieId, movie.Name, movie.Year.ToString(), movie.ImageUrl, movie.Genre, movie.Producer, movie.Description, movie.Actors, movie.Duration.ToString(), m, 0, 0);
                    _notyf.Success("Movie edited.");
                }
                else
                {
                    if (String.IsNullOrEmpty(Request.Form["episode"]))
                    {
                        throw new Exception("You must enter an episode");
                    }
                    if (String.IsNullOrEmpty(Request.Form["season"]))
                    {
                        throw new Exception("You must enter an episode");
                    }

                    int episode = Convert.ToInt32(Request.Form["episode"]);
                    int season = Convert.ToInt32(Request.Form["season"]);
                    _movieService.EditMovieOrEpisode(HttpContext.Session.GetLoggedUser(), movieId, movie.Name, movie.Year.ToString(), movie.ImageUrl, movie.Genre, movie.Producer, movie.Description, movie.Actors, movie.Duration.ToString(), m, season, episode);
                    _notyf.Success("Episode edited.");
                }
                return RedirectToPage("/Movies/MovieDetails", new { m = m, movieId = movieId });
            }
            catch (Exception ex)
            {
                _notyf.Error(ex.Message);
                return Page();
            }
        }
    }
}

WatchedItWeb/Pages/Movies/MovieDetails.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using ClassLibraries.models;
using ClassLibraries.services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ClassLibraries.interfaces;

namespace WatchedItWeb.Pages.Movies
{
    public class MovieDetailsModel : PageModel
    {
        private readonly INotyfService _notyf;
        private readonly IMovieService _movieService;
        private readonly IEpisodeService _episodeService;

        [BindProperty(SupportsGet = true)]
        public int movieId { get; set; }

        [BindProperty(SupportsGet = true)]
        public bool m { get; set; }

        [BindProperty(SupportsGet = true)]
        public int CurrentPage { get; set; } = 0;

        [BindProperty]
        public Review review { get; set; }

        public Movie movie { get; set; }
        public List<Review> reviews { get; set; } = new List<Review>();




        public MovieDetailsModel(INotyfService notyf, IMovieService movieService, IEpisodeService episodeService)
        {
            _notyf = notyf;
            _movieService = movieService;
            _episodeService = episodeService;
        }
        public IActionResult OnGet()
        {
            try
            {
                if (m)
                {
                    movie = _movieService.GetMovieById(movieId);
                }
                else
                {
                    movie = _episodeService.GetEpisodeById(movieId);
                }
        
                if (movie == null)
                {
                    _notyf.Error("Resource not found!");
                    return RedirectToPage("/Movies/AllMovies");
                }
                if (HttpContext.Session.GetLoggedUser() != null)
                {
                    Review ownReview = ReviewService.GetReview(HttpContext.Session.GetLoggedUser(), movieId);
                    if (ownReview != null)
                    {
                        reviews.Add(ownReview);
                    }
                }
                List<Review> loadedReviews = new List<Review>();
                for (int i = 0; i <= CurrentPage; i++)
                {
                    loadedReviews = ReviewService.GetReviews(HttpContext.Session.GetLoggedUser() == null ? 0 : HttpContext.Session.GetLoggedUser().Id, movieId, i * 4);
                    reviews.AddRange(loadedReviews);
                }
                return Page();
            }
            catch (Exception ex)
            {
                _notyf.Error(ex.Message);
                return RedirectToPage("/Index");
            }
        }

        public IActionResult OnPostOnDelete()
        {
            try
            {
                _movieService.DeleteMovieOrEpisode(HttpContext.Session.GetLoggedUser(), movieId);
                if (m)
                {
                    _notyf.Success("Movie deleted");
                    return RedirectToPage("/Movies/AllMovies");
                }
                else
                {
                    int seriesId = Convert.ToInt32(Request.Form["seriesId"]);
                    _notyf.Success("Episode deleted");
                    return RedirectToPage("/Serie/SeriesDetails", new { seriesId = seriesId });
                }
            }
            catch (Exception ex)
            {
                _notyf.Error(ex.Message);
                return RedirectToPage($"/Movies/MovieDetails", new { m = m, movieId = movieId });
            }

        }
        public IActionResult OnPostOnSubmitReview()
        {
            try
            {
                ReviewService.PostReview(HttpContext.Session.GetLoggedUser(), movieId, review.Description, review.Rating);
                _notyf.Success("Review posted");
                return RedirectToPage($"/Movies/MovieDetails", new { m = m, movieId = movieId });
            }
            catch (Exception ex)
            {
                _notyf.Error(ex.Message);
                return RedirectToPage($"/Movies/MovieDetails", new { m = m, movieId = movieId});
            }
        }
        public IActionResult OnPostOnDeleteReview()
        {
            try
            {
                int reviewId = Convert.ToInt32(Request.Form["reviewId"]);
                ReviewService.DeleteReview(HttpContext.Session.GetLoggedUser(), reviewId);
                _notyf.Success("Review deleted");
                return RedirectToPage($"/Movies/MovieDetails", new { m = m, movieId = movieId });
            }
            catch (Exception ex)
            {
                _notyf.Error(ex.Message);
                return RedirectToPage($"/Movies/MovieDetails", new { m = m, movieId = movieId });
            }  
        }
    }
}

WatchedItWeb/Pages/Movies/AddMovie.cshtml
@page
@model WatchedItWeb.Pages.Movies.AddMovieModel
@using ClassLibraries.models
@{
}

<div class="wrapper">
    <form method="post" class="auth">
        <fieldset>
            <legend>Add @(Model.m == false ? "Episode" : "Movie")</legend>
            <div class="field">
                <input type="text" asp-for="movie.Name">
                <label asp-for="movie.Name">Name *</label>
            </div>
            <div class="field">
                <input type="date" asp-for="movie.Year">
                <label asp-for="movie.Year">Year *</label>
            </div>
            <div class="field">
                <input type="text" asp-for="movie.ImageUrl">
                <label asp-for="movie.ImageUrl">Image URL</label>
            </div>
            <div class="field">
                <input type="text" asp-for="movie.Genre">
                <label asp-for="movie.Genre">Genre *</label>
            </div>
            <div class="field">
                <input type="text" asp-for="movie.Producer">
                <label asp-for="movie.Producer">Producers *</label>
            </div>
            <div class="field">
                <textarea asp-for="movie.Description" rows="10"></textarea>
                <label asp-for="movie.Description">Description</label>
            </div>
            <div class="field">
                <textarea asp-for="movie.Actors" rows="8"></textarea>
                <label asp-for="movie.Actors">Actors *</label>
            </div>
            <div class="field">
                <input type="text" asp-for="movie.Duration">
                <label asp-for="movie.Duration">Duration * HH:MM:SS</label>
            </div>
            @if (!Model.m)
            {
                <div class="field-special">
                    <div class="field-special-half">
                        <input type="number" name="season" id="season">
                        <label for="season">S *</label>
                    </div>
                    <div class="field-special-half">
                        <input type="number" name="episode" id="episode">
                        <label for="episode">EP *</label>
                    </div>
                </div>
            }
        <div class="field-submit">
            <p class="info">* Field are mandatory!</p>
            <button type="submit">Add</button>
        </div>
        </fieldset>
    </form>
</div>      

WatchedItWeb/Pages/Movies/AllMovies.cshtml
@page
@using ClassLibraries.models
@model WatchedItWeb.Pages.Movies.AllMoviesModel


<div class="wrapper">
    <div class="movies-header">
        <h2 class="heading">All movies</h2>
        <form class="search">
            <input type="text" asp-for="keyword" placeholder="Search...">
            <button type="submit">Go</button>
        </form>
    </div>
    <div class="row">
        @foreach (Movie m in Model.movies)
        {
            <div class="card-movie">
                <a asp-page="/Movies/MovieDetails" asp-route-m="true" asp-route-movieId="@m.Id">
                    <div class="arbox">
                        <div class="media">
                            <img src="@m.ImageUrl" alt="">
                        </div>
                    </div>
                    <p>@m.Name</p>
                </a>
            </div>
        }
        @if (Model.keyword == null)
        {
            <a asp-route-currentpage="@(Model.CurrentPage + 1)" class="load-more">Load more...</a>
        }
    </div>
</div>

WatchedItWeb/Pages/Movies/EditMovie.cshtml
@page "{m}/{movieId}"
@model WatchedItWeb.Pages.Movies.EditMovieModel
@using ClassLibraries.models
@{
}

<div class="wrapper">
    <form method="post" class="auth">
        <fieldset>
            <legend>Edit @(Model.movie.GetType() == typeof(Episode) ? "Episode" : "Movie")</legend>
            <div class="field">
                <input type="text" asp-for="movie.Name">
                <label asp-for="movie.Name">Name *</label>
            </div>
            <div class="field">
                <input type="date" asp-for="movie.Year">
                <label asp-for="movie.Year">Year *</label>
            </div>
            <div class="field">
                <input type="text" asp-for="movie.ImageUrl">
                <label asp-for="movie.ImageUrl">Image URL</label>
            </div>
            <div class="field">
                <input type="text" asp-for="movie.Genre">
                <label asp-for="movie.Genre">Genre *</label>
            </div>
            <div class="field">
                <input type="text" asp-for="movie.Producer">
                <label asp-for="movie.Producer">Producers *</label>
            </div>
            <div class="field">
                <textarea asp-for="movie.Description" rows="10"></textarea>
                <label asp-for="movie.Description">Description</label>
            </div>
            <div class="field">
                <textarea asp-for="movie.Actors" rows="8"></textarea>
                <label asp-for="movie.Actors">Actors *</label>
            </div>
            <div class="field">
                <input type="text" asp-for="movie.Duration">
                <label asp-for="movie.Duration">Duration * HH:MM:SS</label>
            </div>
            @if (!Model.m)
            {
                <div class="field-special">
                    <div class="field-special-half">
                        <input type="number" name="season" id="season" />
                        <label for="season">S *</label>
                    </div>
                    <div class="field-special-half">
                        <input type="number" name="episode" id="episode" />
                        <label for="episode">EP *</label>
                    </div>
                </div>
            }
            <div class="field-submit">
                <p class="info">* Fields are mandatory!</p>
                <button type="submit">Edit</button>
            </div>
        </fieldset>
    </form>
</div>      

WatchedItWeb/Pages/Movies/MovieDetails.cshtml
@page "{m}/{movieId}"
@model WatchedItWeb.Pages.Movies.MovieDetailsModel
@using ClassLibraries.models
@{
}
<div class="wrapper">
    <div class="movie-details">
        <div class="moviepic">
            <div class="media">
                <img src="@Model.movie.ImageUrl" alt="">
            </div>
        </div>
        <div class="movie-description">
            <h3>
                @Model.movie.Name - @if (Model.movie is Episode)
            {
                @:Season
                @(((Episode)Model.movie).SeasonNo.ToString());
                @:Episode
                @(((Episode)Model.movie).EpisodeNo.ToString());
            }
            </h3>
            <div class="desc-header">
                <p>@Model.movie.Year.Year</p>
                <p>@Model.movie.Genre</p>
                <p>@Model.movie.Rating / 5</p>
            </div>
            <div class="desc-desc">
                <p>@Model.movie.Description</p>
            </div>
            <div class="desc-actors">
                <h3>@Model.movie.Duration.Hours Hours @Model.movie.Duration.Minutes minutes</h3>
                <div class="producers">
                    <h4>Producers:</h4>
                    @foreach (string item in Model.movie.Producer.Split("\r\n"))
                    {
                        <p>@item</p>
                    }
                </div>
                <div class="actors">
                    <h4>Starring:</h4>
                    @foreach (string item in Model.movie.Actors.Split("\r\n"))
                    {
                        <p>@item</p>
                    }
                </div>
            </div>
            @if (HttpContext.Session.GetLoggedUser()?.IsAdmin == true)
            {
                <div class="controls">
                    <a asp-page="/Movies/EditMovie" asp-route-movieId="@Model.movie.Id" asp-route-m="@(Model.movie.GetType() == typeof(Episode) ? false : true)">Edit</a>
                    <form method="post">
                        @if (Model.movie is Episode)
                        {
                            <input type="hidden" name="seriesId" value="@(((Episode)Model.movie).SeriesId)" />
                        }
                        <button type="submit" asp-page-handler="OnDelete">Delete</button>
                    </form>
                </div>
            }
            @if (HttpContext.Session.GetLoggedUser() != null)
            {
                <div class="leave-review">
                    <h4>Leave review</h4>
                    <form method="post" class="flat">
                        <div class="media">
                            <img src="@HttpContext.Session.GetLoggedUser().ImageUrl" onerror=this.src="../../../images/default-user-image.png">
                        </div>
                        <textarea placeholder="Description" class="review-desc" type="text" asp-for="review.Description"></textarea>
                        <input placeholder="rating" class="stars" type="number" asp-for="review.Rating" min="1" max="5">
                        <button type="submit" asp-page-handler="OnSubmitReview">Send</button>
                    </form>
                </div>
            }
        </div>
        <div class="reviews">
            <h3>Reviews</h3>
            @foreach (Review r in Model.reviews)
            {
                <div class="review">
                    <div class="review-header">
                        <div class="media">
                            <img src="@r.UserImg" onerror=this.src ="../../../images/default-user-image.png">
                        </div>
                        @if (r.UserId == HttpContext.Session.GetLoggedUser()?.Id)
                        {
                            <p>You</p>
                        }
                        else
                        {
                            <p>@r.FirstName @r.LastName</p>
                        }

                        <p>@r.Rating/5</p>

                        @if (HttpContext.Session.GetLoggedUser()?.IsAdmin == true || HttpContext.Session.GetLoggedUser()?.Id == r.UserId)
                        {
                            <form method="post">
                                <input type="hidden" name="reviewId" value="@r.Id" />
                                <button class="delete-review" type="submit" asp-page-handler="OnDeleteReview">Delete</button>
                            </form>
                        }

                    </div>
                    <div class="review-content">
                        <p>@r.Description</p>
                    </div>
                </div>
            }
            @if (Model.reviews.Count == 0)
            {
                <p>This movie currently has no reviews.</p>
            }
            else
            {
                <a asp-route-currentpage="@(Model.CurrentPage + 1)" class="load-more">Load more...</a>
            }

        </div>
    </div>
</div>